### ISSUE TITLE
electrum.configure-builder unable to download electrum

### ISSUE THREAD

**Issue by seven-beep** [ben-grande/qusal#104]
### Commitment

I confirm that I have read the following resources:

*   [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
*   [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
*   [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
*   [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
*   [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version
e1dcf0722f9e56df5c51ddcb5b9007135ccdd54e

### Brief summary

Applying electrum.configure-builder to disp-electrum-builder will on Electrum download.

This is this snippet:

```` yaml
## file.managed does not fetch URLs through a SocksProxy.
"{{ slsdotpath }}-download":
  cmd.run:
    - require:
      - file: "{{ slsdotpath }}-make-download-dir"
    - name: |
        timeout --foreground 1200 curl.anondist-orig \
          --connect-timeout 60 \
          --tlsv1.3 --proto =https \
          --fail --fail-early \
          --proxy "socks5h://10.152.152.10:9400" \
          --parallel --parallel-immediate \
          --no-progress-meter --silent --show-error \
          -O "{{ electrum_url_archive }}" \
          -O "{{ electrum_url_sig }}"
    - cwd: /tmp/electrum-download
    - runas: user
````

I think you hardcoded the ip `10.152.152.10`, which should not work for installations.  What was the problematic around this download to use a custom proxy ?

**Comment by ben-grande** [comment]
Unspecific to this issue, I somehow my Salt installation [is broken](https://github.com/QubesOS/qubes-issues/issues/9532) for a few days, so I can't Salt anything.

The address is valid in whonix, it is mapped to the gateway by firewall rules. What is failing there is the port, 9400, as the state is incomplete not calling `sys-bitcoin.configure-gateway` to add the torrc and firewall configuration. This possibly implicates other formulas that uses the `sys-bitcoin-gateway`.

To see the `10.152.151.10` rule on the Whonix-Workstation:
```sh
nft -s list chain inet filter output
```
