### ISSUE TITLE
Improve documentation regarding Salt

### ISSUE THREAD

**Issue by peakunshift** [ben-grande/qusal#20]
### Commitment

I confirm that I have read the following resources:

- [x] [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)

- [x] [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)

- [x] [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)

- [x] [Could you please make my preference the defafault?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Current problem (if any)

Salt can be difficult at first for users unfamiliar with it. The goal here might not be to write a full tutorial, but writing some basic info could help better understanding how it works, how to use it and some specific explanations for this project.

### Proposed solution

Add a Salt document in the `docs` folder with quick introduction, resources, tips and tricks and explanations about how it's used in this project.
Also, update all `qubesctl` commands to add `sudo` as it's required to run the command.

### The value to a user, and who that user might be

Salt being the main tool here, it helps the user better understand the project and thus facilitate contributions.

**Comment by ben-grande** [comment]
The use of Salt in this project doesn't deviate from what Salt already provides, there is still much of Salt expressions that I have not used it yet.

I agree to add the documentation focusing on the use of Salt on this project, more specifically why some things are the way they are.

**Comment by peakunshift** [comment]
Some links for references (that you already know :upside_down_face:):
- https://forum.qubes-os.org/t/qubes-salt-beginners-guide/20126
- https://www.qubes-os.org/doc/salt/
- https://github.com/unman/shaker
- https://github.com/unman/notes
- https://github.com/QubesOS/qubes-issues/issues/8218

The guides are really clear and easy to follow, enough to better understand Qusal!
