### ISSUE TITLE
Unman cacher has been updated for fix multiple pending issues

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#23]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

https://github.com/unman/shaker/tree/main/cacher

### Brief summary

Nftables, fedora and mirrors have been fixed upstream

**Comment by tlaurion** [comment]
Nevermind. I just saw you recent commits since last time I tried to deploy sys-cacher from qusal. Will give it another shot later on! Thanks for your awesome project!

**Comment by ben-grande** [comment]
I had already done nftables some months ago, I updated mirrors recently.

Please report back if the issues were fixed, Zchunk errors stills haunts the Fedora templates from time to time.
