### ISSUE TITLE
sys-cacher : uninstallation doesn't work

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#35]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

[af27eb1](https://github.com/ben-grande/qusal/commit/af27eb131d09aaaf14c20e7cd5b444e76fce8008)

### Brief summary

Still having issues deploying sys-cacher correctly (tem[lates still hit tinyproxy which fails translating http->https).
Consequently, uninstalling was attempted and fails.

### Steps to reproduce

```
[user@dom0 ~/QubesIncoming/heads-tests-deb12-nix/qusal(main)]
$ qubesctl top.enable sys-cacher.deinit
local:
    ----------
    sys-cacher.deinit.top:
        ----------
        status:
            enabled
[user@dom0 ~/QubesIncoming/heads-tests-deb12-nix/qusal(main)]
$ qubesctl --templates state.apply
[WARNING ] top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order.
[CRITICAL] Rendering SLS 'base:sys-cacher.untag' failed: could not find expected ':'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:sys-cacher.untag' failed: could not find expected ':'
DOM0 configuration failed, not continuing
[user@dom0 ~/QubesIncoming/heads-tests-deb12-nix/qusal(main)]
(1)$ qubesctl state.apply sys-cacher.remove-policy
local:
----------
          ID: sys-cacher-absent-rpc-policy
    Function: file.absent
        Name: /etc/qubes/policy.d/75-sys-cacher.policy
      Result: True
     Comment: Removed file /etc/qubes/policy.d/75-sys-cacher.policy
     Started: 15:03:52.522713
    Duration: 26.476 ms
     Changes:   
              ----------
              removed:
                  /etc/qubes/policy.d/75-sys-cacher.policy

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  26.476 ms
[user@dom0 ~/QubesIncoming/heads-tests-deb12-nix/qusal(main)]
$ qubesctl state.apply sys-cacher.untag
[CRITICAL] Rendering SLS 'base:sys-cacher.untag' failed: could not find expected ':'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:sys-cacher.untag' failed: could not find expected ':'
DOM0 configuration failed, not continuing

```

### Expected behavior

 applying deinstallation steps from README should work as described

### Actual behavior

seems like syntax errors are present and fails from untag.

**Comment by ben-grande** [comment]
The `untag` issue is fixed now.

If you have time, I'd greatly appreciate more information on the issues you encountered with using the cacher so I can fix it. I don't encounter such issues and I use it a lot on Debian and some Fedora templates.
