### ISSUE TITLE
drop unmaintained hardened-kernel

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#4]
https://github.com/ben-grande/qusal/blob/main/salt/kicksecure-minimal/install.sls

Just installing the package by default does effectively nothing.

Understanding, maintaining, using scripts in https://github.com/Kicksecure/hardened-kernel/tree/master/usr/share/hardened-kernel folder would be required.

That's the reason why it's not installed by default in Kicksecure yet. Because development stalled, currently not maintained, unclear future.

**Comment by ben-grande** [comment]
> That's the reason why it's not installed by default in Kicksecure yet. Because development stalled, currently not maintained, unclear future.

Instead of adding to testing, as upstream development has stalled, I will be removing it.
