### ISSUE TITLE
Add Tailscale formula

### ISSUE THREAD

**Issue by ben-grande** [ben-grande/qusal#42]
### Current problem (if any)

Remote management on restricted network is difficult:

- Tunneling SSH is difficult and requires a public managed node;
- Opening ports on the router and allowing traffic to flow to the self-hosted VPN; and
- Creating a hidden service with Tor or I2P is slow and can have credentials authentication (Onion Authentication) but easier than all the other self-hosted methods;

### Proposed solution

Add [tailscale](https://github.com/ben-grande/qusal/issues/34#issuecomment-2011887695).

Adding tailscale to a qube can be a security concern. Your OpenID provider can authenticate to your machine, but your can also use your own OpenID instance. Using Tailscale does not open ports to the internet, only your configured nodes can access it, so less dangerous than opening ports on your router in this metric.

The installation will of course be optional and restricted to the qubes you want to have it.

### The value to a user, and who that user might be

Users can remotely manage remote qubes and non-qubes more easily without having to setup their tunnel, be it self-hosted VPN, VPS with SSH Tunnel or Hidden service with Onion Authentication.

.

**Comment by ben-grande** [comment]
Just an update on this. I have produced what I would say is an almost finished formula. I have not released it cause I didn't test as I didn't create a Tailscale account.

**Comment by kennethrrosen** [comment]
@ben-grande  Happy to test with my account if that would be helpful.

**Comment by ben-grande** [comment]
Please test the formula. I created an account to test and it was useful... else I would deliver something broken as I had to fix some things.

**Comment by ben-grande** [comment]
> @ben-grande Happy to test with my account if that would be helpful.

Can you please test?

**Comment by kennethrrosen** [comment]
Works as expected @ben-grande many thanks!

As a thought experiment, is there any concievable way of splitting this: say, having users connect a disposable to sys-tailscale mesh network without the disposable having tailscale itself?

**Comment by ben-grande** [comment]
Possible if following the [Tailscale subnet guide](https://tailscale.com/kb/1019/subnets), untested. Converting `sys-tailscale` to provide network also needs to be done.

The problem is some things needs to be done on the Admin interface rather than on the qube side...
