### ISSUE TITLE
Add recipe to deploy qubes-video-companion for screensharing/videoconferencing

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#49]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Current problem (if any)

Sharing screens/webcam for people doing videoconferencing or live screensharing is complicated under Qubes.
https://github.com/QubesOS/qubes-video-companion resolved that.

But its not installed by default. qusal offers the possibility to do it easily and do the right thing creating the proper qubes to do ti efficiently.

### Proposed solution

Another out of the box inexperience.

### The value to a user, and who that user might be

User: ability to use camera easily
Documentarists: now they can use qubes-screenshot merged into dom0 deployment. But creating screencast videos is still convulated.
Developers: Easily share workflow leading to an error in github issues, screeencasting directly a single window content for recording, with/without sound.

**Comment by tlaurion** [comment]
Not sure how to propose the proper way to do this though. It's a two part thing, dom0+template installation

**Comment by tlaurion** [comment]
https://github.com/QubesOS/qubes-issues/issues/9147

**Comment by ben-grande** [comment]
> But its not installed by default. qusal offers the possibility to do it easily and do the right thing creating the proper qubes to do ti efficiently.

It won't be present in the default installation (explained at the bottom of this post).

> ### Proposed solution
> Another out of the box inexperience.

Possible.

> ### The value to a user, and who that user might be
> User: ability to use camera easily
> Documentarists: now they can use qubes-screenshot merged into dom0 deployment. But creating screencast videos is still convulated.
> Developers: Easily share workflow leading to an error in github issues, screeencasting directly a single window content for recording, with/without sound.

Thanks for writing this with details, it is important.

> Not sure how to propose the proper way to do this though. It's a two part thing, dom0+template installation.

The Dom0 part is easy. The Template part for use with devices will be targetting `sys-usb` formula, the template `tpl-sys-usb` (optional installation of video-companion) at least in the documentation side, this way, you can target any other template with it:
```sh
qubesctl --skip-dom0 --targets=QUBE state.apply video-companion.install
```
 
> Seems like the workflow I see here is to add this in the default templates (xfce) so the companion is available into standard qubesos deployment vs in minimal templates cloned and specialized? Throughts?

It will not be added to the default template by me for two reasons:

- It's a WIP, that probably why it is not installed in the full template by default (Qubes OS decision);
- Qusal doesn't install anything on the default templates, to always clone from a clean slate/template.

**Comment by tlaurion** [comment]
Just make sure that you understand that qubes-video-companion needs to run in stream "receiver" qube (where vidéo would be stored, where the videoconference will happen) and fbe qubes selected by the app is where the stream originates from.

https://github.com/QubesOS/qubes-issues/issues/7991#issuecomment-2073621648

**Comment by ben-grande** [comment]
I am not sure it makes sense to create qubes for this package. What do you think?

Qusal already has things that can be used for sharing and receiving, such as browser and signal. The state that install the qubes-video-companion will target those qubes (at user's will, not by default).

**Comment by tlaurion** [comment]
As discussed it might make sense to think of integrating obs since the most ideal stream aggregate here to advance what was presented by @deeplow https://m.youtube.com/watch?v=_UxndcxIngw&t=20052s, without the whole video editing with dgpu pass-through.

Just being able to stream screen capture and my videocam with voice would be good enough to do short, unedited videos in my use case.

**Comment by ben-grande** [comment]
How did you install in Debian? Flatpak, Debian repo or Ubuntu PPA?

- Flatpak I won't consider this time, I am avoiding it as the update method is not integrated in Qubes;
- Debian repo should be the best, but I am afraid from time to time it can get old on Debian freezes before new major releases; and
- Ubuntu PPA is [not vetted by Ubuntu](https://help.ubuntu.com/community/PPA), but it is an [official build by the OBSProject](https://github.com/obsproject/obs-studio/wiki/install-instructions#ubuntu) maintained by [one of it's members](https://github.com/Gol-D-Ace), so it is not a random PPA or less trusted than OBS itself, [PPA link](https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio). Didn't test if the PPA works on Debian, maybe it is not build with Debian in mind, just Ubuntu.

Debian releases are 1 year behind upstream, which for some software, it can make a great difference. I don't have much experience with OBS to justify the PPA, unless security patches are made much earlier to the Ubuntu PPA than to the Debian repos.

**Comment by ben-grande** [comment]
OBS is a client, every client has a formula, `signal`, `browser`, `media` etc. Please open an new issue about OBS if you want it.
