### ISSUE TITLE
qvm-screenshot tool missing region selection that was available in original version

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#51]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Current problem (if any)

an option to qvm-screenshot is missing so that keyboard shortcut + mouse interaction permits to select region on the screen to be the only selected input to be copied to destination qube as screenshot, as opposed to pass whole dom0 screenshot of qubes whole window and have to edit that screenshot to crop to arrive to the same result, incurring unecesary steps to arrive to the same result.

### Proposed solution

Offer an option to make --region screenshot possible as upstream original qvm-screenshot tool to assign shortcut and use mouse to draw rectangle on screen to not have to use dom0 fullscreen or the whole qube window as a screenshot

### The value to a user, and who that user might be

devels: have only relevant part of the screen be captured to quickly post on github issue
documentarist: be able to only select part of a screen to focus from macro <-> micro perspectives to help end users follow what is important in created doc
ux designer: create canvas based on actual UX and desired UX by just changing actual to desired GUI for changes and quicly iterate
Me: I have to do edit windows capture manually, which makes me loose precious time which could be done at the source otherwise.

**Comment by ben-grande** [comment]
The tools scrot and maim have the following behavior: if you select region or window on the dialog, it has two options, you click to select a whole window or you click and drag to select a region.

The tools spectacle and xfce4-screenshooter are different, spectacle is a little more complicated and xfce4-screenshooter does allow only selecting the window or the region. Spectacle benefits is editing in Dom0 and is KDE native, but just UX related.

Do you agree that moving scrot and maim as preferred is the best behavior? `scrot` actually messes up the region drawing and I think it is a bug in it, `maim` seems the best option.

Please try the different tools with the `-S` option
```sh
qvm-screenshot -S maim
```

and report back what you find more usable. Don't need to test every tool

**Comment by ben-grande** [comment]
I will commit with `maim`, but reports are appreciated.

**Comment by ben-grande** [comment]
Rerun dom0.screenshot to install maim and update the screenshot script.
