### ISSUE TITLE
Fix typos in sys-git/install-client-proxy.sls and sys-usb/install-client-proxy.sls

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#56]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

@ben-grande as a "thank you" note, see title of this bug :) 

In both cases: `mab-db` -> `man-db`.

**Comment by ben-grande** [comment]
Thanks.
