### ISSUE TITLE
gpg: no running gpg-agent

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#64]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)

### Question

After going through the `state` path of installing the formulas for `sys-pgp`, I went through the setup guide from [here](https://github.com/ben-grande/qubes-app-linux-split-gpg2). Everything was fine until the below happened.

On `dev-companyA`:
```shell_session
% gpg -vvv -K
gpg: using character set 'utf-8'
gpg: using pgp trust model
gpg: key 55CCE0FCC9033EEA: accepted as trusted key
gpg: key 2D4ADD0F4B0E5019: accepted as trusted key
gpg: no running gpg-agent - starting '/usr/share/split-gpg2/gpg-agent-placeholder'
gpg: waiting for the agent to come up ... (5s)
gpg: waiting for the agent to come up ... (4s)
gpg: waiting for the agent to come up ... (3s)
gpg: waiting for the agent to come up ... (2s)
gpg: waiting for the agent to come up ... (1s)
gpg: can't connect to the agent: End of file
gpg: no running gpg-agent - starting '/usr/share/split-gpg2/gpg-agent-placeholder'
gpg: waiting for the agent to come up ... (5s)
gpg: waiting for the agent to come up ... (4s)
gpg: waiting for the agent to come up ... (3s)
gpg: waiting for the agent to come up ... (2s)
gpg: waiting for the agent to come up ... (1s)
gpg: can't connect to the agent: End of file
```
Verified the `dom0` for `qvm-service` on the `dev-companyA` qube:
```shell_session
$ qvm-service dev-companyA
split-gpg2-client    on
qusal-proxy-client  on
crond  on 
```

Verified the `journalctl /usr/bin/qrexec-policy | grep -i gpg`:
```shell_session
qubes.Gpg: dev -> sys-pgp: denied: no matching rule found
```
Nothing on `qubes.Gpg2`.

Also noticed:
On `dev-companyA`: 
```shell_session
% gpg --version
gpg (GnuPG) 2.2.40
```
On sys-pgp:
```shell_session
$ gpg --version
gpg (GnuPG) 2.4.4
```

Policy on `dom0`:
```shell_session
qubes.Gpg2 + dev-companyA @default allow target=sys-pgp 
qubes.Gpg2 * @anyvm @default ask target=sys-pgp default_target=sys-pgp
qubes.Gpg2 * @anyvm @anyvm   `deny`
```
What did I miss this time?

**Comment by ben-grande** [comment]
> ### Commitment
> I confirm that I have read the following resources:
> 
> * [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
> * [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
> * [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
> 
> ### Question
> After going through the `state` path of installing the formulas for `sys-pgp`, I went through the setup guide from [here](https://github.com/ben-grande/qubes-app-linux-split-gpg2). Everything was fine until the below happened.

That upstream link is wrong, it should be the `QubesOS` repo instead of mine, will fix.

> On `dev-companyA`:
> 
> ```
> % gpg -vvv -K
> gpg: using character set 'utf-8'
> gpg: using pgp trust model
> gpg: key 55CCE0FCC9033EEA: accepted as trusted key
> gpg: key 2D4ADD0F4B0E5019: accepted as trusted key
> gpg: no running gpg-agent - starting '/usr/share/split-gpg2/gpg-agent-placeholder'
> gpg: waiting for the agent to come up ... (5s)
> gpg: waiting for the agent to come up ... (4s)
> gpg: waiting for the agent to come up ... (3s)
> gpg: waiting for the agent to come up ... (2s)
> gpg: waiting for the agent to come up ... (1s)
> gpg: can't connect to the agent: End of file
> gpg: no running gpg-agent - starting '/usr/share/split-gpg2/gpg-agent-placeholder'
> gpg: waiting for the agent to come up ... (5s)
> gpg: waiting for the agent to come up ... (4s)
> gpg: waiting for the agent to come up ... (3s)
> gpg: waiting for the agent to come up ... (2s)
> gpg: waiting for the agent to come up ... (1s)
> gpg: can't connect to the agent: End of file
> ```

On `dev-companyA`:
```sh
systemctl --user status split-gpg2-client
```

> Verified the `journalctl /usr/bin/qrexec-policy | grep -i gpg`:
> 
> ```
> qubes.Gpg: dev -> sys-pgp: denied: no matching rule found
> ```
>
> Nothing on `qubes.Gpg2`.

`qubes.Gpg` is the wrong service, it should be `qubes.Gpg2`. Why it is calling the wrong service I don't know yet.

Run:
```sh
alias gpg   # show if gpg is aliased
\gpg -vvv -K    # run gpg without functions or aliases, so from PATH
```
 
> Also noticed: On `dev-companyA`:
> 
> ```
> % gpg --version
> gpg (GnuPG) 2.2.40
> ```
> 
> On sys-pgp:
> 
> ```
> $ gpg --version
> gpg (GnuPG) 2.4.4
> ```
> 
> Policy on `dom0`:
> 
> ```
> qubes.Gpg2 + dev-companyA @default allow target=sys-pgp 
> qubes.Gpg2 * @anyvm @default ask target=sys-pgp default_target=sys-pgp
> qubes.Gpg2 * @anyvm @anyvm   `deny`
> ```

The rest seems fine.

**Comment by wassp-ds** [comment]
> qubes.Gpg is the wrong service, it should be qubes.Gpg2. Why it is calling the wrong service I don't know yet.

I also don't have a default `dev` qube and I have not touched anything `Gpg` related. Only the upstream docs.

> Run:

alias gpg   # show if gpg is aliased
\gpg -vvv -K    # run gpg without functions or aliases, so from PATH

`gpg` is not aliased, `which` points to `/usr/bin/gpg`
`\gpg -vvv -K` <- same errors as above

**Comment by ben-grande** [comment]
https://github.com/ben-grande/qusal/issues/64#issuecomment-2181027969

On dev-companyA:
```sh
systemctl --user status split-gpg2-client
```

**Comment by wassp-ds** [comment]
> [#64 (comment)](https://github.com/ben-grande/qusal/issues/64#issuecomment-2181027969)
> 
> On dev-companyA:
> 
> ```shell
> systemctl --user status split-gpg2-client
> ```

active and running

**Comment by ben-grande** [comment]
Please follow this guide
https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOTING.md#qrexec-client-shows-request-refused

**Comment by wassp-ds** [comment]
Everything seems fine, except:
on `dev-companyA`:

```shell_session
% qrexec-client-vm @default qubes.Gpg2
Error in a config file, aborting
```

**Comment by ben-grande** [comment]
Thanks for the debugging info. Issue has been fixed. Pull `qusal` again and apply the `sys-pgp.configure` state to `sys-pgp`.

**Comment by radek-otee** [comment]
@ben-grande post-fix towards accepting empty values results in:
```shell_session
% gpg -vvv --list-secret-keys
gpg: using character set 'utf-8'
gpg: using pgp trust model
gpg: key 55CCE0FCC9033EEA: accepted as trusted key
gpg: key 2D4ADD0F4B0E5019: accepted as trusted key
gpg: connection to agent is in restricted mode
```
