### ISSUE TITLE
Kicksecure template update/upgrade fails if user does not have/use sys-cacher

### ISSUE THREAD

**Issue by kennethrrosen** [ben-grande/qusal#66]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

R4.2.1

### Brief summary

Kicksecure template repo salt config/state fails when attempting to upgrade packages. The salt configuration assumes the user is using/desires to use sys-cacher.

### Steps to reproduce

Follow guidelines and steps in README.md. Run `sudo qubesctl --targets=kicksecure-17-minimal state.apply`

### Expected behavior

Finish updating template without issues.

### Actual behavior

Discover that repos have been changed to `http://HTTPS///` and that sys-cacher-config is failing because user is not using sys-cacher.
.

**Comment by ben-grande** [comment]
Thanks. I will correct it on multiple formulas together with a detection
mechanism to check if repos should be rewritten or not.

**Comment by ben-grande** [comment]
As we are not in production, you will have to revert to a good state manually:
```sh
sudo qubesctl --skip-dom0 --targets=kicksecure-17-minimal state.apply sys-cacher.uninstall-client
```
