### ISSUE TITLE
test LKRG kernel module being loaded

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#7]
* Check APT log mentioning dkms to see if the kernel module is being successfully compiled.
* Check if the kernel module is even loaded.

https://www.kicksecure.com/wiki/Linux_Kernel_Runtime_Guard_LKRG#Debugging

**Comment by ben-grande** [comment]
Not being loaded and broke the GUI somehow, will be moved to non-default state.

```
root@kicksecure-17-minimal:~# modinfo p_lkrg
modinfo: ERROR: Module p_lkrg not found.
root@kicksecure-17-minimal:~# dkms status
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/lkrg/0.9.6.2/source/dkms.conf)
lkrg/0.9.6.2, 6.1.62-1.qubes.fc37.x86_64, x86_64: installed
tirdad/0.1, 6.1.62-1.qubes.fc37.x86_64, x86_64: installed
```
