### ISSUE TITLE
split-gpg2 client does not show keys imported in sys-pgp

### ISSUE THREAD

**Issue by radek-otee** [ben-grande/qusal#73]
### Commitment

I confirm that I have read the following resources:

- [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

Qubes OS 4.2.1

### Steps to reproduce

```shell_session
% gpg -vvv --list-secret-keys
gpg: using character set 'utf-8'
gpg: using pgp trust model
gpg: key XXXXXXXXXXXX: accepted as trusted key
gpg: key XXXXXXXXXXXX: accepted as trusted key
gpg: connection to agent is in restricted mode
```

### Expected behavior

Expected to see the imported keys upon `gpg -K`

### Actual behavior

No output, or the output above with higher verbosity.

.

**Comment by ben-grande** [comment]
On `sys-pgp`:

```sh
cd ~/.gnupg/split-gpg/CLIENTQUBE
gpg --homedir . --list-secret-keys
```

On `CLIENTQUBE`
```sh
gpg -K
```

Did you import the public key to `CLIENTQUBE`?

You can redact the key information with XXXXX as you did above.

**Comment by radek-otee** [comment]
@ben-grande 

Went through the following steps:
```shell_session
sys-pgp$ gpg --export > public-keys-export
sys-pgp$ gpg --export-ownertrust > ownertrust-export
sys-pgp$ qvm-copy public-keys-export ownertrust-export

dev$ gpg --import ~/QubesIncoming/sys-pgp/public-keys-export
dev$ gpg --import-ownertrust ~/QubesIncoming/sys-pgp/ownertrust-export
```
And no keys visible with `gpg -K`

**Comment by ben-grande** [comment]
On `sys-pgp`:

```
cat ~/.config/qubes-split-gpg2/qubes-split-gpg2.conf
cat ~/.config/sh/profile.d/split-gpg2.sh
```

On `dev`:

```sh
gpg -vvv --list-secret-keys
```

**Comment by radek-otee** [comment]
> On `sys-pgp`:
> 
> ```
> cat ~/.config/qubes-split-gpg2/qubes-split-gpg2.conf

[DEFAULT]
autoaccept = 86400
pksign_autoaccept = 86400
pkdecrypt_autoaccept = 86400
verbose_notifications = yes
allow_keygen = no
#gnupghome =
isolated_gnupghome_dirs = ~/.gnupg/split-gpg
#debug_log =
#source_keyring_dir =

> cat ~/.config/sh/profile.d/split-gpg2.sh

export GSK_RENDERER=cairo LIBGL_ALWAYS_SOFTWARE=1

> zenity --question --title title --text text

libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
Couldn't open libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
Aborted (core dumped)

> On `dev`:
> gpg -vvv --list-secret-keys

```shell
% gpg -vvv -K
gpg: using character set 'utf-8'
gpg: using pgp trust model
gpg: key XXXXXXXXXXXXXXXX: accepted as trusted key
gpg: key XXXXXXXXXXXXXXXX: accepted as trusted key
gpg: connection to agent is in restricted mode
```

**Comment by ben-grande** [comment]
>Couldn't open libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
Aborted (core dumped)

This is the error, thanks for sharing, issue has been fixed. Commit will come soon.
