### ISSUE TITLE
ansible fails at ansible.configure because of non-existent file

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#79]
### Commitment

I confirm that I have read the following resources:

- [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

R4.2.1

### Brief summary

Configuration crashes on `configure` step.  

### Steps to reproduce

`sudo qubesctl --skip-dom0 --targets=ansible state.apply ansible.configure,zsh.touch-zshrc`

This is on top of the bug reported [here](https://github.com/ben-grande/qusal/issues/78#issue-2371688751).

### Expected behavior

Configuration step completed

### Actual behavior

Culprit: no such file in the path
"{{ slsdotpath }}-ssh-config":
  file.managed:
    - name: /home/user/.ssh/config
    `- source: salt://{{ slsdotpath }}/files/server/ssh-config`
    - file_mode: '0600'
    - dir_mode: '0700'
    - user: root
    - group: root
    - makedirs: True

.

**Comment by ben-grande** [comment]
I simplified the ansible formula. Now it uses functions from `sys-ssh`.
