### ISSUE TITLE
install tirdad instead of tirdad-dkms

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#8]
That is the way it is usually done on Debian.

(By comparison, one installs `virtualbox` instead of `virtualbox-dkms`.)

**Comment by ben-grande** [comment]
This is already the case:
https://github.com/ben-grande/qusal/blob/e35c9fbf4b4ca1044167acee2c431efdcb656012/salt/kicksecure-minimal/install.sls#L35

Please close if resolved.
