### ISSUE TITLE
dotfiles git configuration with qusal

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#84]
### Commitment

I confirm that I have read the following resources:

- [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Question
DISCLAIMER: not sure whether this fits better under this or the dotfiles repo. Happy to move it where appropriate.

I am using the combination of your `qusal` and `dotfiles` repos, as I find them a fantastic combo. Can you explain what the intended setup is for the use of `gpg` functionality with `git` is?

.

**Comment by ben-grande** [comment]
On the [git config](https://github.com/ben-grande/dotfiles/blob/main/files/git/.config/git/config), search for the following keywords: `sign`, `verify`, `gpg` (beware of false positives such as `signOff` and `signatre`, `signatureFile`).

The intended workflow is:

- sign all commits andl tags  (auto)
- sign pushes if the remote supports it  (auto)
- verify merge signature before merge occurs (auto)
- aliases to verify commits and tags (manual, requires user explicit action to call the alias)

**Comment by wassp-ds** [comment]
thanks - will try it out!
