### ISSUE TITLE
fix typos in sys-ssh-agent README.md

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#87]
### Commitment

I confirm that I have read the following resources:

- [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Brief summary

Change all instances of `qusal-ssh-agent-forwarder` to `qubes-ssh-agent-forwarder`

### Expected behavior

Setup works out of the box when following the `README` steps.

### Actual behavior

Following the steps directly causes the client set up to fail.

.

**Comment by ben-grande** [comment]
> Change all instances of `qusal-ssh-agent-forwarder` to `qubes-ssh-agent-forwarder`

Change from `qubes-` to `qusal-` was intentional to create a distinction of Qubes services vs Qusal services.

> Following the steps directly causes the client set up to fail.

Can you be more verbose? I don't have a way to debug based on this.

**Comment by ben-grande** [comment]
Try running the `sys-ssh-agent` steps again though:
```
sudo qubesctl --skip-dom0 --targets=tpl-sys-ssh-agent sys-ssh-agent.install
sudo qubesctl --skip-dom0 --targets=tpl-dev dev.install
```

**Comment by wassp-ds** [comment]
What I am doing is playing dumb and blindly copying and pasting the commands from subsequent `README`s to see whether the instructions make sense. In this instance, following the instructions client-side:

```shell_session
% sudo systemctl --no-block restart qusal-ssh-agent-forwarder@personal.service
Failed to restart qusal-ssh-agent-forwarder@personal-dev.service: Unit qusal-ssh-agent-forwarder@personal.service not found.
```
after the set up `sys-ssh-agent` is complete. Pointing it to `qubes-ssh-agent-forwarder`, the mechanism works as intended. I guess the missing step in the doc is either what you suggested above and it would work out of the box, or there is an extra step missing of turning the service on, client side. Or something else :smile:

**Comment by ben-grande** [comment]
Did you restart the qubes after modifications are done to the templates?
Restart dev.

**Comment by wassp-ds** [comment]
After reboot it works - can you include that in the documentation as part of the process (if you haven't already)?

**Comment by ben-grande** [comment]
> After reboot it works - can you include that in the documentation as part of the process (if you haven't already)?

That is standard Qubes OS usage, after changes are done to the template, template based qubes must be restarted.
