### ISSUE TITLE
Usage of tmux-sorcerer and tmux plugins?

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#97]
### Commitment

I confirm that I have read the following resources:

*   [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
*   [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
*   [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
*   [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
*   [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Question

Not a priority, but curiosity. I needed to use console multiplexer, thought of using tmux and realized its not under dom0 but qusal deploys a tmux-sorcerer script. Looked at the code and then discovered that tmux had plugins. Not a tmux practicioner but looking to do asciinema of all things happening under different qubes linked to wyng use cases over boroadband, local network and be able to quickly present differences and areas of needed optimizations.

What are your use cases for tmux-sorcerer?
Thanks!

**Comment by ben-grande** [comment]
tmux-sorcerer is an alternative to [Tmux Plugin Manager](https://github.com/tmux-plugins/tpm), but doesn't try to fetch it over the internet. You are responsible to put the plugins in place as well as verifying their integreity.

Reasoning for it's existence: TPM does not do GPG signature verification and I don't like being few keybinds away from the plugins being installed and updated.

It is similar to vim-pathogen but for Tmux.

**Comment by ben-grande** [comment]
Closing as there was no further discussion.
