### ISSUE TITLE
Where to put the qusal.conf file ?

### ISSUE THREAD

**Issue by 3isenHeiM** [ben-grande/qusal#99]
### Commitment

I confirm that I have read the following resources:

*   [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
*   [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
*   [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
*   [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
*   [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Question

I'm missing a step in the deployment of qusal on a test machine.

Where do I need to set the file `minions.d/qusal.conf` ?

Furthermore, after enabling the user-dirs (and doing some research), it apprears that the custom salt config needs to be placed in `/srv/user_salt` and `/srv/user_pillars`. How to configure these user-dirs to be placed elsewhere ?

Thanks!

**Comment by ben-grande** [comment]
It is placed to /etc/salt/minion.d after running the step 6

https://github.com/ben-grande/qusal/blob/main/docs/INSTALL.md#dom0-installation

Copy the project to the Salt directories:

~/QubesIncoming/"${qube}"/qusal/scripts/setup.sh

There is no need to use /srv/user_*, it is just an alternative path and its
implementation was broken for a long time, therefore we use /srv/salt/qusal.

You can configure the path by editing qusal.conf and putting the
directories on the place you desire, but then you are by yourself during
updates.

**Comment by 3isenHeiM** [comment]
Thanks!
